import Mathlib
open Topology Uniformity

example [TopologicalSpace X] [PseudoMetricSpace Y] {F: ι → X → Y}
  (hF: ∀i, Continuous (F i)) (tendsto_F : TendstoUniformly F f l) [l.NeBot] : Continuous f :=
  continuous_iff_continuousAt.mpr fun x ↦ Metric.tendsto_nhds.mpr fun ε ε_pos ↦
  let ε3 := ε/3
  have ε3_pos: ε3 > 0 := div_pos ε_pos three_pos
  let ⟨i, hi⟩ := Metric.tendstoUniformly_iff.mp tendsto_F ε3 ε3_pos |>.exists
  have := Metric.continuous_iff'.mp (hF i) x ε3 ε3_pos
  this.mono fun y h ↦ calc
    _ ≤ dist (f y) (F i y) + dist (F i y) (F i x) + dist (F i x) (f x) := dist_triangle4 ..
    _ < ε3 + ε3 + ε3 := add_lt_add
      (add_lt_add (hi y) h)
      (dist_comm .. |>.trans_lt <| hi x)
    _ = ε := add_thirds ε

example [TopologicalSpace X] [UniformSpace Y] {F: ι → X → Y}
  (hF: ∀ᶠi in l, Continuous (F i)) (tendsto_F : TendstoUniformly F f l) [l.NeBot] : Continuous f :=
  continuous_iff_continuousAt.mpr fun x ↦ Uniform.continuousAt_iff'_right.mpr fun _s hs ↦
  let ⟨v, v_mem, v_symm, hv3s⟩ := comp_comp_symm_mem_uniformity_sets hs
  let ⟨_I₁, hI₁l, hI₁⟩: ∃I ∈ l, ∀i ∈ I, ∀y, (f y, F i y) ∈ v := tendsto_F v v_mem |>.exists_mem
  let ⟨_I₂, hI₂l, hI₂⟩: ∃I ∈ l, ∀i ∈ I, ∀ᶠy in 𝓝 x, (F i x, F i y) ∈ v :=
    hF.mono (fun _ h ↦ Uniform.continuous_iff'_right.mp h x v_mem) |>.exists_mem
  let ⟨i, hi₁, hi₂⟩ := l.nonempty_of_mem <| l.inter_mem hI₁l hI₂l
  have : ∀ᶠy in 𝓝 x, (f x, f y) ∈ v ○ v ○ v := Filter.Eventually.mono (hI₂ i hi₂)
    fun y hy ↦ ⟨F i y, ⟨F i x, hI₁ i hi₁ x, hy⟩, v_symm.mk_mem_comm.mp <| hI₁ i hi₁ y⟩
  this.mono fun _ h ↦ hv3s h

-- annotated version :)
/- note about `Filter.Eventually`:
For `p: ι → Prop` and `l: Filter ι`, `∀ᶠi in l, p i` means that `p` is _eventually_ true along `l`,
i.e. for sufficiently "large" i (with respect to l). The direct translation is `{i | p i} ∈ l`,
or equivalently `∃v ∈ l, ∀i ∈ v, p i`.
Ex: for `l: Filter ℕ := Filter.atTop` (the filter generated by intervals [0, n] representing
a limit → ∞), `∀ᶠi in l, p i` means `∃N, ∀n ≥ N, p n`.
Ex: `Filter.Tendsto f (𝓝 x) (𝓝 y)` (f approaches y at x) ↔ `∀V ∈ 𝓝 y, ∀ᶠa in 𝓝 x, f a ∈ V`,
i.e. `∀V ∈ 𝓝 y, ∃U ∈ 𝓝 x, ∀a ∈ U, f a ∈ V`
Also, `Filter.Eventually.mono` maps eventualities across implications:
`(∀ᶠx in l, p x) → (∀x, p x → q x) → ∀ᶠx in l, q x`
-/

example
  {X Y ι: Type*} -- spaces X and Y, indexing type ι
  [TopologicalSpace X] [UniformSpace Y]
  {F: ι → X → Y} -- our "sequence" of functions is an arbitrary ι-indexed family
  {f: X → Y}
  {l: Filter ι} -- l is the ι-"sequence" along which F_i approaches f, like .atTop for →∞
  (tendsto_F : TendstoUniformly F f l)
  (hF: ∀ᶠi in l, Continuous (F i)) -- F_i is eventually continuous (a ∀i would be so impatient)
  [l.NeBot] -- sets in l are nonempty (if ∅ ∈ l, then l would contain all sets)
  : Continuous f :=
  /-
  Continuity in uniform spaces is equivalent to `∀a: X, Filter.Tendsto (f a, f ·) (𝓝 a) (𝓤 Y)`,
  so `∀s ∈ 𝒰 Y, (f a, f ·) ⁻¹' s ∈ 𝓝 a` ↔ `∀s ∈ 𝒰 Y, ∀ᶠb in 𝓝 a, (f a, f b) ∈ s`.
  `𝒰 Y: Filter (Y × Y)` is the filter of entourages in Y, the defining structure of a uniform space,
  which are kind of like (generated by, for metric spaces) `{(a, b) | dist a b < ε}`).
  This is a lot like saying "f a is eventually s-close to f y for any closeness s"
  -/
  Uniform.continuous_iff'_right.mpr fun a _s hs ↦
  /-
  this is like a triple triangle inequality for uniform spaces, where from our entourage `s ∈ 𝒰 Y`
  we can get a smaller entourage `v ∈ 𝒰 Y`, such that `v ○ v ○ v ⊆ s` (where `○` is composition of
  relations `A ○ B = {(a, b) | ∃c, (a, c) ∈ A ∧ (c, b) ∈ B}`), with the added property that
  `v` is symmetric `(a, b) ∈ v ↔ (b, a) ∈ v`. This is a lot like getting an ε/3-ball from an ε-ball.
  -/
  let ⟨(v: Set (Y × Y)), (v_mem: v ∈ 𝓤 Y), (v_symm: IsSymmetricRel v), (hv3s: v ○ v ○ v ⊆ _s)⟩ :=
    comp_comp_symm_mem_uniformity_sets hs
  -- now, we get two useful sets of ιs in l (kind of like thresholds in a sequence)
  /- first, since F uniformly tends to f along l, we can get an `I₁ ∈ l` such that for all the
  `i ∈ I₁` ("after" the threshold set by I), every `b: X` satisfies `(f b, F i b)` ∈ v, i.e.
  `f b` is "v-close" ("ε/3-close") to `F i b`.
  -/
  let ⟨_I₁, hI₁l, hI₁⟩: ∃I ∈ l, ∀i ∈ I, ∀b, (f b, F i b) ∈ v := tendsto_F v v_mem |>.exists_mem
  /- the next set of ιs we get is from the fact that F is eventually continuous, using the same
  uniform space formulation of continuity as before, so for all the `i ∈ I₂`,
  `F i a` is eventually v-close to `F i b` along `𝓝 a`, i.e. `∃U ∈ 𝓝 a, ∀b ∈ U, ...`.
  -/
  let ⟨_I₂, hI₂l, hI₂⟩: ∃I ∈ l, ∀i ∈ I, ∀ᶠb in 𝓝 a, (F i a, F i b) ∈ v :=
    hF.mono (fun _ h ↦ Uniform.continuous_iff'_right.mp h a v_mem) |>.exists_mem
  /- now that we have these two useful regions of ι, we take the `i: ι` that we'll actually use
  from the intersection `I₁ ∩ I₂`, which is guaranteed to exist because
  `I₁ ∩ I₂ ∈ l` (by filter axioms) and `∀I ∈ l, I.Nonempty` because of our `l.NeBot` assumption.
  -/
  let ⟨i, hi₁, hi₂⟩ := l.nonempty_of_mem <| l.inter_mem hI₁l hI₂l
  -- first, we use the I₂ property to get `F i a` eventually v-close to `F i b` along `𝓝 a`
  have : ∀ᶠb in 𝓝 a, (F i a, F i b) ∈ v := hI₂ i hi₂
  /- now, we actually use that triangle-inequality-esque property of v (well, the triangle part) to
  get `f a` eventually v³-close to `f b` along `𝓝 a`:
  `(f a, F i a) ∈ v` from `i ∈ I₁`,
  `(F i a, F i b) ∈ v` from the `i ∈ I₂` we just used, and then
  `(F i b, f b) ∈ v` from `i ∈ I₁` again and the symmetry we required of `v`.
  -/
  have : ∀ᶠb in 𝓝 a, (f a, f b) ∈ v ○ v ○ v := this.mono fun b hb ↦
    ⟨F i b, ⟨F i a, hI₁ i hi₁ a, hb⟩, v_symm.mk_mem_comm.mp <| hI₁ i hi₁ b⟩
  -- now, we use the inequality part (v³ ⊆ s) to get `∀ᶠb in 𝓝 a, (f a, f b) ∈ s`. QED :)
  this.mono fun _ h ↦ hv3s h

namespace Dini
open Filter
variable {X ι} [TopologicalSpace X] [Preorder ι]

example {F: ι → X → ℝ} (hF_mono: Monotone F) (hf_cont: Continuous f)
  (h_tendsto: ∀x, Tendsto (F · x) atTop (𝓝 (f x))) (hF_cont: ∀i, Continuous (F i)) :
  TendstoLocallyUniformly F f atTop := atTop.eq_or_neBot.elim
    (fun h ↦ tendstoLocallyUniformly_iff_forall_tendsto.mpr fun _ ↦ h ▸ bot_prod ▸ tendsto_bot)
  fun [_] ↦ Metric.tendstoLocallyUniformly_iff.mpr fun ε ε_pos a ↦
  have hF_le (i) : (F i) ≤ f := fun x ↦ ge_of_tendsto (h_tendsto x) <|
    eventually_ge_atTop i |>.mono fun _ ↦ (hF_mono · x)
  let G i := f - (F i)
  have hG_eq {i x} : dist (f x) (F i x) = G i x := abs_of_nonneg <| sub_nonneg.mpr <| hF_le i x
  have hG_cont i : Continuous (G i) := hf_cont.sub <| hF_cont i
  let E i := (G i) ⁻¹' .Iio ε
  have hE_open i : IsOpen (E i) := isOpen_Iio.preimage <| hG_cont i
  have : .univ ⊆ ⋃i, E i := fun x _ ↦
    let ⟨i, hi⟩ := Metric.tendsto_nhds.mp (h_tendsto x) ε ε_pos |>.exists
    ⟨E i, ⟨i, rfl⟩, hi.trans_eq' <| dist_comm .. |>.trans hG_eq |>.symm⟩
  have hE_mono : Monotone E :=
    have hG_anti : Antitone G := hF_mono.neg.const_add f
    have : Antitone (Set.preimage · (.Iio ε)) := fun _ _ ↦ (· · |>.trans_lt)
    this.comp hG_anti
  -- have hE_dir : Directed (· ⊆ ·) E := hE_mono.directed_le
  -- let ⟨i, hi⟩ := CompactSpace.isCompact_univ.elim_directed_cover E hE_open this hE_dir
  -- eventually_ge_atTop i |>.mono fun j hj x ↦ hG_eq.trans_lt <| hE_mono hj <| hi trivial
  let ⟨_S, ⟨i, (hi: E i = _S)⟩, hS⟩ := this <| Set.mem_univ a
  have hEi : E i ∈ 𝓝 a := hE_open i |>.mem_nhds <| hi.symm.subset hS
  ⟨E i, hEi, eventually_ge_atTop i |>.mono fun _j hj _x hx ↦ hG_eq.trans_lt <| hE_mono hj hx⟩

variable {Y} [NormedAddCommGroup Y] [Lattice Y] [HasSolidNorm Y] [IsOrderedAddMonoid Y]

theorem dini_local {F: ι → X → Y} (hF_mono: Monotone F) (hf_cont: Continuous f)
  (h_tendsto: ∀x, Tendsto (F · x) atTop (𝓝 (f x))) (hF_cont: ∀i, Continuous (F i)) :
  TendstoLocallyUniformly F f atTop := atTop.eq_or_neBot.elim
    (fun h ↦ tendstoLocallyUniformly_iff_forall_tendsto.mpr fun _ ↦ h ▸ bot_prod ▸ tendsto_bot)
  fun [_] ↦ Metric.tendstoLocallyUniformly_iff.mpr fun ε ε_pos a ↦
  have hF_le (i) : (F i) ≤ f := fun x ↦
    -- ge_of_tendsto (h_tendsto x) <|
    -- eventually_ge_atTop i |>.mono fun _ ↦ (hF_mono · x)
    sorry
  let G i x := ‖(f - (F i)) x‖
  have hG_eq {i x} : dist (f x) (F i x) = G i x := dist_eq_norm ..
  have hG_cont i : Continuous (G i) := continuous_norm.comp <| hf_cont.sub <| hF_cont i
  let E i := (G i) ⁻¹' .Iio ε
  have hE_open i : IsOpen (E i) := isOpen_Iio.preimage <| hG_cont i
  have : .univ ⊆ ⋃i, E i := fun x _ ↦
    let ⟨i, hi⟩ := Metric.tendsto_nhds.mp (h_tendsto x) ε ε_pos |>.exists
    ⟨E i, ⟨i, rfl⟩, hi.trans_eq' <| dist_comm .. |>.trans hG_eq |>.symm⟩
  have hE_mono : Monotone E :=
    have {i} : G i = (‖·‖) ∘ (f - (F i)) := rfl
    have : G = ((‖·‖) ∘ ·) ∘ (f - F ·) := rfl
    have unga : Monotone ((‖·‖) ∘ ·) := fun f g hfg x ↦
      by
      dsimp

      sorry
    have : Antitone (f - F ·) := (funext fun i ↦ sub_eq_add_neg f (F i)) ▸ hF_mono.neg.const_add f
    have hG_anti : Antitone G := Monotone.comp_antitone unga this
    have : Antitone (Set.preimage · (.Iio ε)) := fun _ _ ↦ (· · |>.trans_lt)
    this.comp hG_anti
  -- have hE_dir : Directed (· ⊆ ·) E := hE_mono.directed_le
  -- let ⟨i, hi⟩ := CompactSpace.isCompact_univ.elim_directed_cover E hE_open this hE_dir
  -- eventually_ge_atTop i |>.mono fun j hj x ↦ hG_eq.trans_lt <| hE_mono hj <| hi trivial
  let ⟨_S, ⟨i, (hi: E i = _S)⟩, hS⟩ := this <| Set.mem_univ a
  have hEi : E i ∈ 𝓝 a := hE_open i |>.mem_nhds <| hi.symm.subset hS
  ⟨E i, hEi, eventually_ge_atTop i |>.mono fun _j hj _x hx ↦ hG_eq.trans_lt <| hE_mono hj hx⟩

end Dini
